version: '2.2'

services:
  postgres:
    image: postgres:11
    restart: 'no'
    logging:
      driver: none
    environment:
      POSTGRES_DB: pageview
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: pageview
    volumes:
      - ./docker/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U cexprd']
      interval: 2s
      timeout: 5s
      retries: 30
  pageview:
    image: dronbas/api:1.0
    restart: 'no'
    environment:
      PG_HOST: postgres
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
